version: "3.9"

services:
  api:
    env_file: ./.env.production
    container_name: api
    image: test/dolado:1.0.0
    build: .
    ports:
      - $PORT_PRODUCTION:$PORT_PRODUCTION
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT_PRODUCTION
    depends_on:
      - db
  db:
    env_file: ./.env.production
    container_name: db
    image: mysql:5.7
    ports:
      - $DB_PORT_LOCAL:$DB_PORT_PRODUCTION
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}