version: "3.9"

services:
  api:
    container_name: api
    image: test/dolado:1.0.0
    build: .
    ports:
      - "3300:3300"
    environment:
      - DB_HOST=db
      - DB_USER=mysql
      - DB_PASSWORD=mysql
      - DB_NAME=dolado
      - DB_PORT=3306
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=dolado
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}